#!/bin/bash

trap "kill 0" SIGINT

export CWD=$PWD

if [ "$1" = "dev" ]
then
    (gulp &)
else
    (gulp > /dev/null 2>&1 &)
fi

sleep 1.5

cd app

export FLASK_APP=app
export FLASK_DEBUG=1

if [ -z "$1" ] || [ "$1" == "dev" ]
then
    export TLPY_PATH="${CWD}/untitled.tlpy"
else
    export TLPY_PATH="$CWD/$1"
fi

if [ "$1" = "dev" ]
then
    (flask run &)
else
    (flask run > /dev/null 2>&1 &)
fi

python -m webbrowser "http://127.0.0.1:5000/"

cd $CWD

read